// Authentication
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAIL = 'AUTH_REGISTER_FAIL';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// Calendars
export const CALENDAR_LOAD_USER_SUCCESS = 'CALENDAR_LOAD_USER_SUCCESS';

export const CALENDAR_SET_DAY = 'CALENDAR_SET_DAY';
export const CALENDAR_ADD_DAY = 'CALENDAR_ADD_DAY';
export const CALENDAR_ADD_WEEK = 'CALENDAR_ADD_WEEK';
export const CALENDAR_ADD_MONTH = 'CALENDAR_ADD_MONTH';
export const CALENDAR_ADD_YEAR = 'CALENDAR_ADD_YEAR';
export const CALENDAR_VIEW = 'CALENDAR_VIEW';
export const CALENDAR_LOAD_EVENTS = 'CALENDAR_LOAD_EVENTS';

export const CALENDAR_VIEW_TYPE_YEAR = 'CALENDAR_YEAR';
export const CALENDAR_VIEW_TYPE_MONTH = 'CALENDAR_MONTH';
export const CALENDAR_VIEW_TYPE_WEEK = 'CALENDAR_WEEK';
export const CALENDAR_VIEW_TYPE_DAY = 'CALENDAR_DAY';