// Authentication
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAIL = 'AUTH_REGISTER_FAIL';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// Calendars
export const CALENDAR_LOAD_USER_SUCCESS = 'CALENDAR_LOAD_USER_SUCCESS';
export const CALENDAR_SET_DAY = 'CALENDAR_SET_DAY';
export const CALENDAR_SET_MONTH = 'CALENDAR_SET_MONTH';
export const CALENDAR_SET_YEAR = 'CALENDAR_SET_YEAR';
export const CALENDAR_VIEW_DAY = 'CALENDAR_VIEW_DAY';
export const CALENDAR_VIEW_WEEK = 'CALENDAR_VIEW_WEEK';
export const CALENDAR_VIEW_MONTH = 'CALENDAR_VIEW_MONTH';
export const CALENDAR_VIEW_YEAR = 'CALENDAR_VIEW_YEAR';